name: "Lint and Test"
description: "Sets up Python, installs dependencies, lints, tests, and uploads code coverage."
inputs:
  python-version:
    description: "Python version to use"
    required: true
  codecov-token:
    description: "Codecov token (optional for public repos)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==2.2.1
        poetry install --no-root --with dev
      shell: bash

    - name: Lint code
      run: make lint
      shell: bash

    - name: Run tests
      run: make test
      shell: bash

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        token: ${{ inputs.codecov-token }}
