name: Run Tests on Non-Main Branches

on:
  push:
#    paths:
#      - "asgi_logging_middleware/**"
#      - "tests/**"

  workflow_dispatch:
    inputs:
      python-version:
        description: "Select Python version"
        required: false
        default: "3.12"
      branch:
        description: "Select branch"
        required: false
        default: "main"

jobs:
  run-tests:
    name: "Python ${{ matrix.python-version }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Python tests
        uses: ./.github/actions/lint-and-test
        with:
          python-version: ${{ matrix.python-version }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}